// Agent 4 — Spending Coach (PRD §8.2)
// Read-only daily insights generated by Claude from last 30 days of txns.
// One agent_action row PER insight so T1's feed renders them as individual cards.

import { createServiceClient, startAction, logStep, markRunning, markSucceeded } from '@fa/db';
import type { TransactionRow } from '@fa/db/types';
import { defineAgent, type AgentDefinition } from '@fa/inngest';
import { call as claudeCall, FAST_MODEL } from '@fa/claude';
import { monthOverMonthDeltas } from './analyzer';

export interface SpendingCoachInput {
  /** ISO override for tests. */
  now?: string;
}

export interface SuggestedRule {
  trigger: 'monthly_spend_threshold' | 'transaction_categorized';
  condition: { field: string; op: 'gt' | 'gte' | 'lt' | 'lte'; value: number };
  action: 'notify' | 'create_insight';
}

export interface Insight {
  title: string;
  body: string;
  impactDollars: number;
  suggestedRule?: SuggestedRule;
}

export interface SpendingCoachData {
  insightsCount: number;
  insightActionIds: string[];
}

function todayKey(now: Date): string {
  return now.toISOString().slice(0, 10);
}

export const spendingCoachAgent: AgentDefinition<SpendingCoachInput> = defineAgent<SpendingCoachInput>({
  type: 'spending_coach',
  actionType: 'insight',
  requiresApproval: false,
  idempotencyKey: (i) => {
    const now = i.now ? new Date(i.now) : new Date();
    return `insight:${todayKey(now)}`;
  },
  run: async (input, ctx) => {
    const now = input.now ? new Date(input.now) : new Date();
    const since = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

    await ctx.log('pull:start', true, { since: since.toISOString() });
    const txns = await pullLast30Days(ctx.userId, since);
    await ctx.log('pull:done', true, { count: txns.length });

    const insights = await generateInsights(txns, now);
    await ctx.log('claude:done', true, { count: insights.length });

    const insightActionIds: string[] = [];
    for (const ins of insights) {
      const actionId = await persistInsightAction(ctx.userId, ctx.agentId, ins, now);
      insightActionIds.push(actionId);
    }
    await ctx.log('persist:done', true, { count: insightActionIds.length });

    const data: SpendingCoachData = {
      insightsCount: insights.length,
      insightActionIds,
    };
    return { roi: null, data: data as unknown as Record<string, unknown> };
  },
});

async function pullLast30Days(userId: string, since: Date): Promise<TransactionRow[]> {
  const supabase = createServiceClient();
  const { data, error } = await supabase
    .from('transactions')
    .select('*')
    .eq('user_id', userId)
    .gte('date', since.toISOString().slice(0, 10))
    .order('date', { ascending: false });
  if (error) throw new Error(`pullLast30Days ${error.message}`);
  return (data ?? []) as TransactionRow[];
}

/** Exposed for tests. Calls Claude with a JSON-only contract. */
export async function generateInsights(
  txns: TransactionRow[],
  now: Date = new Date(),
): Promise<Insight[]> {
  if (txns.length === 0) return [];

  const deltas = monthOverMonthDeltas(txns, now).slice(0, 8);

  const system =
    'You are a personal-finance spending coach. Given the user\'s month-over-month ' +
    'category spending deltas, identify 1-3 actionable insights ranked by impact. ' +
    'Each insight MUST be JSON. Respond with a JSON object: ' +
    '{"insights": [{"title": string, "body": string, "impactDollars": number, ' +
    '"suggestedRule": {"trigger": "monthly_spend_threshold"|"transaction_categorized", ' +
    '"condition": {"field": string, "op": "gt"|"gte"|"lt"|"lte", "value": number}, ' +
    '"action": "notify"|"create_insight"} }]}. ' +
    'Never invent numbers. Use only the deltas provided. Body must be 1 sentence.';

  const user = JSON.stringify({ deltas });

  const res = await claudeCall({
    model: FAST_MODEL,
    system,
    user,
    maxTokens: 800,
    temperature: 0.3,
    tag: 'spending_coach',
  });

  const parsed = safeParseInsights(res.text);
  return parsed.slice(0, 3);
}

function safeParseInsights(text: string): Insight[] {
  try {
    // Tolerate models that fence JSON.
    const stripped = text.replace(/^```(?:json)?/i, '').replace(/```$/i, '').trim();
    const obj = JSON.parse(stripped) as { insights?: unknown };
    if (!obj || !Array.isArray(obj.insights)) return [];
    const out: Insight[] = [];
    for (const raw of obj.insights) {
      if (!raw || typeof raw !== 'object') continue;
      const r = raw as Record<string, unknown>;
      if (typeof r.title !== 'string' || typeof r.body !== 'string') continue;
      const impact = typeof r.impactDollars === 'number' ? r.impactDollars : 0;
      const ins: Insight = {
        title: r.title,
        body: r.body,
        impactDollars: impact,
      };
      const sr = r.suggestedRule as Record<string, unknown> | undefined;
      if (sr && typeof sr === 'object') {
        const cond = sr.condition as Record<string, unknown> | undefined;
        if (
          (sr.trigger === 'monthly_spend_threshold' || sr.trigger === 'transaction_categorized') &&
          cond && typeof cond.field === 'string' &&
          (cond.op === 'gt' || cond.op === 'gte' || cond.op === 'lt' || cond.op === 'lte') &&
          typeof cond.value === 'number' &&
          (sr.action === 'notify' || sr.action === 'create_insight')
        ) {
          ins.suggestedRule = {
            trigger: sr.trigger,
            condition: { field: cond.field, op: cond.op, value: cond.value },
            action: sr.action,
          };
        }
      }
      out.push(ins);
    }
    return out;
  } catch {
    return [];
  }
}

async function persistInsightAction(
  userId: string,
  agentId: string,
  insight: Insight,
  now: Date,
): Promise<string> {
  const row = await startAction({
    userId,
    agentId,
    agentType: 'spending_coach',
    actionType: 'insight',
    target: insight.title,
    requiresApproval: false,
    idempotencyKey: `insight:${todayKey(now)}:${hash(insight.title)}`,
  });
  await logStep(row.id, {
    step: 'insight:created',
    ok: true,
    detail: {
      title: insight.title,
      body: insight.body,
      impactDollars: insight.impactDollars,
      suggestedRule: insight.suggestedRule ?? null,
    },
  });
  // Insight cards render straight from agent_actions — mark succeeded so the
  // feed picks them up without waiting on a separate worker.
  await markRunning(row.id);
  await markSucceeded(row.id, null);
  return row.id;
}

function hash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) | 0;
  }
  return (h >>> 0).toString(36);
}
