-- Phase 3 / Terminal 2 — seed the cards catalog.
-- Top consumer cards by reward density, covering the categories most likely
-- to dominate a typical user's spend. T4's Credit Card Optimizer joins
-- user spending profiles against this catalog to recommend the optimal mix.
--
-- Rewards shape (jsonb):
--   [{ "category": "Groceries", "multiplier": 4, "cap_annual": 25000 }, ...]
-- Multiplier is expressed as points-per-dollar (or % cash back × 100, same
-- thing since most issuers redeem at ~1¢/point). The optimizer treats it
-- as a raw multiplier — exotic redemption math is out of scope at launch.
--
-- Categories used here match the canonical taxonomy in
-- @fa/claude/src/categorize.ts so the join is direct.
--
-- All inserts are idempotent on (issuer, name). Re-running is safe.

create unique index if not exists cards_issuer_name_uniq on public.cards(issuer, name);

insert into public.cards (name, issuer, network, annual_fee, signup_bonus, rewards, benefits, application_url) values
  ('Sapphire Preferred', 'Chase', 'visa', 95,
   '{"points":60000,"spend_required":4000,"months":3}'::jsonb,
   '[{"category":"Restaurants","multiplier":3},{"category":"Travel","multiplier":2},{"category":"Food Delivery","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["Trip cancellation insurance","Primary rental car insurance"]'::jsonb,
   'https://www.chase.com/sapphire-preferred'),
  ('Sapphire Reserve', 'Chase', 'visa', 550,
   '{"points":60000,"spend_required":4000,"months":3}'::jsonb,
   '[{"category":"Travel","multiplier":3},{"category":"Restaurants","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["$300 travel credit","Priority Pass","Global Entry credit"]'::jsonb,
   'https://www.chase.com/sapphire-reserve'),
  ('Freedom Unlimited', 'Chase', 'visa', 0,
   '{"points":20000,"spend_required":500,"months":3}'::jsonb,
   '[{"category":"Restaurants","multiplier":3},{"category":"Food Delivery","multiplier":3},{"category":"Other","multiplier":1.5}]'::jsonb,
   '["No annual fee"]'::jsonb,
   'https://www.chase.com/freedom-unlimited'),
  ('Freedom Flex', 'Chase', 'mastercard', 0,
   '{"points":20000,"spend_required":500,"months":3}'::jsonb,
   '[{"category":"Restaurants","multiplier":3},{"category":"Food Delivery","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["Rotating 5% categories","No annual fee"]'::jsonb,
   'https://www.chase.com/freedom-flex'),
  ('Ink Business Preferred', 'Chase', 'visa', 95,
   '{"points":100000,"spend_required":8000,"months":3}'::jsonb,
   '[{"category":"Business","multiplier":3,"cap_annual":150000},{"category":"Other","multiplier":1}]'::jsonb,
   '["Business card","Trip cancellation"]'::jsonb,
   'https://www.chase.com/ink-business-preferred'),

  ('Gold Card', 'American Express', 'amex', 325,
   '{"points":60000,"spend_required":6000,"months":6}'::jsonb,
   '[{"category":"Restaurants","multiplier":4,"cap_annual":50000},{"category":"Groceries","multiplier":4,"cap_annual":25000},{"category":"Other","multiplier":1}]'::jsonb,
   '["$120 dining credit","$120 Uber credit"]'::jsonb,
   'https://www.americanexpress.com/gold'),
  ('Platinum Card', 'American Express', 'amex', 695,
   '{"points":80000,"spend_required":8000,"months":6}'::jsonb,
   '[{"category":"Travel","multiplier":5},{"category":"Other","multiplier":1}]'::jsonb,
   '["$200 hotel credit","$200 airline credit","Centurion Lounge","Global Entry"]'::jsonb,
   'https://www.americanexpress.com/platinum'),
  ('Blue Cash Preferred', 'American Express', 'amex', 95,
   '{"points":25000,"spend_required":3000,"months":6}'::jsonb,
   '[{"category":"Groceries","multiplier":6,"cap_annual":6000},{"category":"Subscriptions","multiplier":6},{"category":"Transportation","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["6% grocery cap then 1%","Streaming bonus"]'::jsonb,
   'https://www.americanexpress.com/blue-cash-preferred'),
  ('Blue Cash Everyday', 'American Express', 'amex', 0,
   '{"points":20000,"spend_required":2000,"months":6}'::jsonb,
   '[{"category":"Groceries","multiplier":3,"cap_annual":6000},{"category":"Transportation","multiplier":3,"cap_annual":6000},{"category":"Shopping","multiplier":3,"cap_annual":6000},{"category":"Other","multiplier":1}]'::jsonb,
   '["No annual fee"]'::jsonb,
   'https://www.americanexpress.com/blue-cash-everyday'),
  ('Green Card', 'American Express', 'amex', 150,
   '{"points":40000,"spend_required":3000,"months":6}'::jsonb,
   '[{"category":"Travel","multiplier":3},{"category":"Transportation","multiplier":3},{"category":"Restaurants","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["$189 CLEAR credit","$100 LoungeBuddy credit"]'::jsonb,
   'https://www.americanexpress.com/green'),

  ('Venture X', 'Capital One', 'visa', 395,
   '{"points":75000,"spend_required":4000,"months":3}'::jsonb,
   '[{"category":"Travel","multiplier":10},{"category":"Other","multiplier":2}]'::jsonb,
   '["$300 travel credit","Priority Pass","10k anniversary points"]'::jsonb,
   'https://www.capitalone.com/venture-x'),
  ('Venture Rewards', 'Capital One', 'visa', 95,
   '{"points":75000,"spend_required":4000,"months":3}'::jsonb,
   '[{"category":"Travel","multiplier":5},{"category":"Other","multiplier":2}]'::jsonb,
   '["Global Entry credit"]'::jsonb,
   'https://www.capitalone.com/venture'),
  ('Quicksilver', 'Capital One', 'visa', 0,
   '{"points":20000,"spend_required":500,"months":3}'::jsonb,
   '[{"category":"Other","multiplier":1.5}]'::jsonb,
   '["No annual fee","Flat 1.5% cash back"]'::jsonb,
   'https://www.capitalone.com/quicksilver'),
  ('Savor', 'Capital One', 'mastercard', 95,
   '{"points":30000,"spend_required":3000,"months":3}'::jsonb,
   '[{"category":"Restaurants","multiplier":4},{"category":"Entertainment","multiplier":4},{"category":"Groceries","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["No foreign transaction fees"]'::jsonb,
   'https://www.capitalone.com/savor'),

  ('Double Cash', 'Citi', 'mastercard', 0,
   '{"points":20000,"spend_required":1500,"months":6}'::jsonb,
   '[{"category":"Other","multiplier":2}]'::jsonb,
   '["No annual fee","2% on everything"]'::jsonb,
   'https://www.citi.com/double-cash'),
  ('Custom Cash', 'Citi', 'mastercard', 0,
   '{"points":20000,"spend_required":1500,"months":6}'::jsonb,
   '[{"category":"Top Category","multiplier":5,"cap_annual":6000},{"category":"Other","multiplier":1}]'::jsonb,
   '["5% on highest spend category each month"]'::jsonb,
   'https://www.citi.com/custom-cash'),
  ('Premier', 'Citi', 'mastercard', 95,
   '{"points":75000,"spend_required":4000,"months":3}'::jsonb,
   '[{"category":"Travel","multiplier":3},{"category":"Restaurants","multiplier":3},{"category":"Groceries","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["$100 hotel credit"]'::jsonb,
   'https://www.citi.com/premier'),

  ('Active Cash', 'Wells Fargo', 'visa', 0,
   '{"points":20000,"spend_required":500,"months":3}'::jsonb,
   '[{"category":"Other","multiplier":2}]'::jsonb,
   '["Flat 2% cash back","Cell phone protection"]'::jsonb,
   'https://www.wellsfargo.com/active-cash'),
  ('Autograph', 'Wells Fargo', 'visa', 0,
   '{"points":20000,"spend_required":1000,"months":3}'::jsonb,
   '[{"category":"Restaurants","multiplier":3},{"category":"Travel","multiplier":3},{"category":"Transportation","multiplier":3},{"category":"Subscriptions","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["Cell phone protection"]'::jsonb,
   'https://www.wellsfargo.com/autograph'),

  ('Cash+', 'US Bank', 'visa', 0,
   '{"points":20000,"spend_required":1000,"months":4}'::jsonb,
   '[{"category":"Choice Category 1","multiplier":5,"cap_annual":2000},{"category":"Choice Category 2","multiplier":5,"cap_annual":2000},{"category":"Restaurants","multiplier":2},{"category":"Groceries","multiplier":2},{"category":"Other","multiplier":1}]'::jsonb,
   '["Two 5% choice categories quarterly"]'::jsonb,
   'https://www.usbank.com/cash-plus'),
  ('Altitude Connect', 'US Bank', 'visa', 0,
   '{"points":50000,"spend_required":2000,"months":4}'::jsonb,
   '[{"category":"Travel","multiplier":4},{"category":"Restaurants","multiplier":2},{"category":"Groceries","multiplier":2},{"category":"Subscriptions","multiplier":2},{"category":"Other","multiplier":1}]'::jsonb,
   '["No foreign transaction fees"]'::jsonb,
   'https://www.usbank.com/altitude-connect'),

  ('Premium Rewards', 'Bank of America', 'visa', 95,
   '{"points":60000,"spend_required":4000,"months":3}'::jsonb,
   '[{"category":"Travel","multiplier":2},{"category":"Restaurants","multiplier":2},{"category":"Other","multiplier":1.5}]'::jsonb,
   '["$100 airline credit","Global Entry credit"]'::jsonb,
   'https://www.bankofamerica.com/premium-rewards'),
  ('Customized Cash Rewards', 'Bank of America', 'visa', 0,
   '{"points":20000,"spend_required":1000,"months":3}'::jsonb,
   '[{"category":"Choice Category","multiplier":3,"cap_annual":2500},{"category":"Groceries","multiplier":2,"cap_annual":2500},{"category":"Other","multiplier":1}]'::jsonb,
   '["Pick your 3% category"]'::jsonb,
   'https://www.bankofamerica.com/customized-cash'),

  ('It Cash Back', 'Discover', 'discover', 0,
   '{"points":0,"spend_required":0,"months":12}'::jsonb,
   '[{"category":"Rotating 5%","multiplier":5,"cap_annual":1500},{"category":"Other","multiplier":1}]'::jsonb,
   '["First-year cash back match","Rotating 5% quarters"]'::jsonb,
   'https://www.discover.com/it'),
  ('It Miles', 'Discover', 'discover', 0,
   '{"points":0,"spend_required":0,"months":12}'::jsonb,
   '[{"category":"Travel","multiplier":1.5},{"category":"Other","multiplier":1.5}]'::jsonb,
   '["First-year miles match"]'::jsonb,
   'https://www.discover.com/it-miles'),

  ('Apple Card', 'Goldman Sachs', 'mastercard', 0,
   '{"points":0,"spend_required":0,"months":0}'::jsonb,
   '[{"category":"Apple Pay","multiplier":2},{"category":"Apple Purchases","multiplier":3},{"category":"Other","multiplier":1}]'::jsonb,
   '["Daily Cash","No fees"]'::jsonb,
   'https://www.apple.com/apple-card'),

  ('SoFi Credit Card', 'SoFi', 'mastercard', 0,
   '{"points":0,"spend_required":0,"months":0}'::jsonb,
   '[{"category":"Other","multiplier":2}]'::jsonb,
   '["2% into SoFi invest/save accounts"]'::jsonb,
   'https://www.sofi.com/credit-card'),

  ('Premier Rewards', 'Robinhood', 'visa', 50,
   '{"points":0,"spend_required":0,"months":0}'::jsonb,
   '[{"category":"Other","multiplier":3}]'::jsonb,
   '["3% on everything for Gold members"]'::jsonb,
   'https://www.robinhood.com/credit-card')
on conflict (issuer, name) do nothing;
